version: '3'

services: 
  
  challenge1-project:
    # restart: always
    build: ./challenge1-project
    links:
      - redis
    # command: gunicorn fund.wsgi:application --bind 0.0.0.0:8000
    # volumes:
    #   - ./challenge1-project/Project/static:/djangoApp/Project/static_cdn/static_root
    env_file:
      - ./.env
    expose:
      - "8000"
  

  redis:
    image: 'redis:alpine'
    

  nginx:
    restart: always
    build: ./nginx
    # volumes:
    #   - ./crowd-funding-webapp/Project/static:/static
    ports:
      - '80:80'
  